baseURL = "https://bmhstsa.com/"
DefaultContentLanguage = "en"
languageCode = "en-us"
paginate = 5
theme = "hugo-theme-stack"
title = "BMHS TSA"

googleAnalytics = "G-RS8CPZDN2H"

[permalinks]
post = "/post/:slug/"
page = "/:slug/"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true

  [params.footer]
  since = 2020

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  subtitle = "Battle Mountain High School Technology Student Association"

    [params.sidebar.avatar]
    local = false
    src = "/images/avatar.png"

  [params.article]
  math = false

    [params.article.license]
    enabled = true
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = false

  [params.widgets]
  enabled = [ "search", "archives", "tag-cloud" ]

    [params.widgets.archives]
    limit = 5

    [params.widgets.tagCloud]
    limit = 10

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
pre = "home"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.highlight]
noClasses = false